on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo out a GitHub Actions Secret to the logs
      # - uses: AWSAccountAdministrator/amaliadskaia@opsguru.io
        env:
          AWS_S3_BUCKET: 'bucket-models-sagemaker'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g' 
          echo ${{secrets.AWS_SECRET_ACCESS_KEY}} | sed 's/./& /g'
